apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: dapla-platform
  name:  github-backup
  namespace: dapla-platform
spec:
  image: {{ image }}
  schedule: {{ schedule }}
  timeZone: Europe/Oslo
  ttlSecondsAfterFinished: 300
  resources:
    limits:
      memory: 2Gi
      cpu: "5"
    requests:
      cpu: "500m"
  envFrom:
    - secret: github-backup-config
